### ISSUE TITLE
nm, read the error closer and figured out height of the input video wasn't a multiple of 8

### ISSUE THREAD

**Issue by kalgi13** [OpenVisualCloud/SVT-AV1#652] opened 2019-09-27 05:31 UTC
nm, read the error closer and figured out height of the input video wasn't a multiple of 8
It is still not working, Any other solution ? 

_Originally posted by @singhkays in https://github.com/OpenVisualCloud/SVT-AV1/issues/17#issuecomment-460462627_

**Comment by JackZhouVCD** [comment] 2019-09-27 19:41
possible duplicate of #645

**Comment by kylophone** [comment] 2019-10-03 03:06
fixed by #620

**Closed by kylophone** 2019-10-03 03:06 UTC
