### ISSUE TITLE
[AV1 ffmpeg-plugin]when RC is set to 0, encoding stream happens errors by AV1 ffmpeg-plugin

### ISSUE THREAD

**Issue by waterflag0614** [OpenVisualCloud/SVT-AV1#223] opened 2019-04-15 08:09 UTC
Encoding AV1 stream is  have error information by the following command line.  so that stream cann't be decoded by ffmpeg.

ffmpeg -r 25 -video_size 1920x1080 -pixel_format yuv420p -f rawvideo -i sunflower_1920x1080_500.yuv -c:v libsvt_av1 -qp 31  -preset 8 -r 25  -vframes 250 0001_qp40.ivf -y
error information:
"""
[AVBSFContext @ 0xf2953600] Failed to send packet to filter av1_metadata for stream 0 

[AVBSFContext @ 0xf2953600] Invalid repeated frame header OBU. 

[AVBSFContext @ 0xf2953600] Failed to read unit 0 (type 6). 

[AVBSFContext @ 0xf2953600] Failed to read packet.
"""
when decoded that stream by the following command line(enable libaom).
ffmpeg -i  0001_qp40.ivf -pixel_format yuv420p -f rawvideo out.yuv
"""
[libaom-av1 @ 0x3538100] Failed to decode frame: Corrupt frame detected
[libaom-av1 @ 0x3538100]   Additional information: Keyframe / intra-only frame required to reset decoder state
Error while decoding stream #0:0: Invalid data found when processing input
"""
Encoding stream by the following command line is normal.  the stream can be correct decoded by ffmpeg 
SvtAv1EncApp -i sunflower_1920x1080_500.yuv -w 1920 -h 1080 -fps-num 25 -fps-denom 1 -enc-mode 8 -latency-mode 0 -irefresh-type 2 -q 31 -n 250 -b out.ivf

**Comment by hassount** [comment] 2019-04-25 23:34
@jsunintel

**Comment by xuguangxin** [comment] 2019-12-05 06:11
can't reproduce your issue anymore. could you help double confirm it with latest ffmpeg and svt library @waterflag0614 
thanks

**Comment by hassount** [comment] 2019-12-09 07:31
closing as this does not seem to be reproducible

**Closed by hassount** 2019-12-09 07:31 UTC
Labels: ffmpeg
