### ISSUE TITLE
r2r mismatch

### ISSUE THREAD

**Issue by mtangtencent** [OpenVisualCloud/SVT-AV1#790] opened 2019-11-14 23:03 UTC
It is found that the SVT-AV1 encoder (c177dedf) has r2r mismatch issue when using the following command line
`./SvtAv1EncApp.exe -i FourPeople_1280x720_60.yuv -w 1280 -h 720 -b test.ivf -enc-mode 8 -n 200 -rc 0 -q 40 -intra-period 31`
Even the debug build is not able to produce deterministic outputs.

**Comment by mtangtencent** [comment] 2019-11-14 23:31
I tested this issue using the latest commit (d647dc4fa5). The issue is still there.

**Comment by hassount** [comment] 2019-11-15 00:53
This is a WIP a duplicate issue to #258

**Comment by bzhutencent** [comment] 2019-11-15 21:07
#258 is for encmode[0-2], here encmode is set to 8,  are we sure this is a duplicate?

**Comment by hassount** [comment] 2019-11-19 16:28
let's re-test after #804

**Comment by AlexBoswellVCD** [comment] 2019-12-16 19:14
I can reproduce this with the current master (4814268).

**Comment by AlexBoswellVCD** [comment] 2019-12-16 21:11
I ran a bisect and found this r2r is introduced in (a5dcbf2)

**Comment by hassount** [comment] 2019-12-16 21:16
Cool, can you test disabling that on the latest master?

**Comment by AlexBoswellVCD** [comment] 2019-12-16 22:05
Disabling it gets rid of the r2r macros. More specifically, turning off the following lines while leaving the commit enabled also removes the r2r.
https://github.com/OpenVisualCloud/SVT-AV1/commit/a5dcbf2ecdf6bda7db01aa359fc07e9ad1255871#diff-051be3f82f0c4e17fd579aa4eda9ba62R2295-R2297

**Comment by hassount** [comment] 2019-12-18 23:01
This should now be addressed in the master after f50049aad435b48f1fb7b11402ec44c68b26412f
@bzhutencent can you please confirm ?

**Comment by mtangtencent** [comment] 2019-12-19 01:22
The r2r is already addressed in the latest master. I encoded 480p and 720p videos with preset 4, 6 and 8 for several runs. No r2r mismatch was observed in my experiment.

**Comment by mtangtencent** [comment] 2020-01-10 01:25
Hi @hassount , I observe that there is another r2r mismatch case when using SVT-AV1 0.8.0 (af16f709).
The command line I used is `./SvtAv1EncApp.exe -i ParkScene_1920x1080_24.yuv -w 1920 -h 1080 -b test.ivf -enc-mode 4 -n 200 -rc 0 -q 24 -intra-period 31 -fps-num 24 -fps-denom 1`

**Comment by hassount** [comment] 2020-03-27 15:51
@mtangtencent 
this should be now be addressed by #1143 and #1144

**Comment by hassount** [comment] 2020-04-20 01:20
@mtangtencent I can't reproduce this with the latest master 9ce7f5e
Closing for now, please reopen if you see an issue.

**Closed by hassount** 2020-04-20 01:20 UTC
Labels: bug
