### ISSUE TITLE
poor command line interface

### ISSUE THREAD

**Issue by stax76** [OpenVisualCloud/SVT-AV1#779] opened 2019-11-08 14:27 UTC
There are certain CLI traditions and similarities between x264, x265 and nvencc, following traditions and similarities makes the lives of CLI users and GUI authors easier, knowledge and code could be shared.

1. Executable name should be reasonable short, easy to remember and type, example: git, cmd or wt (new windows terminal)

2. it's a tradition that short switches start with a single dash - and long switches start with double dash -- and there are libraries for parsing, it's OK doing it differently like powershell but in doubt I suggest to follow the tradition.

https://en.wikipedia.org/wiki/Getopt

3. switches should use identical names and parameters as other encoders if possible
https://x265.readthedocs.io/en/latest/cli.html#cmdoption-preset

4. there should be good documentation for both CLI --help, -h and online with anchors, there should be switch type information like int, float etc. and there should be categories like Analysis, Slice Decision, IO, Performance etc.

5. config file and cli parameters should be identical

https://mpv.io/manual/master/#configuration-files

https://github.com/ytdl-org/youtube-dl/blob/master/README.md#configuration

6. switches should have a long version --long and a short version -l and not only one of both.

7. I don't know if it's already supported, y4m input support is important

I'm creator of the oldest and most feature rich encoder GUI staxrip that started 2002 with divx, we've built countless encoder gui's, for av1 so far two, one for aomenc and one for rav1e, both encoders are too slow for end users so it was probably a waste of time, many people request to build a third gui for svt-av1 but I have doubts, a poor cli and poor documentation is an indication that an encoder will fail, maybe nvidia will soon have a better av1 encoder that everybody will use.

Sorry for being so direct and not using more kind language, it's not my strength, due to intuition I'm not very optimistic about svt-av1, I hope that I'm wrong and it will be a success.

**Comment by 1480c1** [comment] 2019-11-08 14:31
> 7\. I don't know if it's already supported, y4m input support is important

y4m is already supported

**Comment by 1480c1** [comment] 2019-11-08 14:34
Afaik, the executable is supposed to be more of an example implementation and this was designed to have the end users use the library directly or through ffmpeg/other wrappers, so probably the design quality of the application was not as high of a priority as much as the quality of the internal encoder itself.

**Comment by moisespr123** [comment] 2019-11-10 18:41
I honestly don't mind about the command line. I also wrote a GUI for SVT-AV1, and it just work fine the way it is.

**Comment by luigi311** [comment] 2019-11-14 01:01
I agree with pretty much everything that was stated, a lot of those standards are utilized everywhere (hence standard) and makes it a lot more intuitive to use the application. I would say that these changes need to be applied prior to the application being permanently integrated to other applications such as ffmpeg. That way if/when the changes are made we will not break support in all those 3rd party applications and require them to re-implement all their mapping and breaking everything. Since we are not yet following the standard it also makes it hard to people to implement support due to the unknown if the application is ever going to switch and risk building support and having it break soon after or in the future.

**Comment by hassount** [comment] 2019-11-15 01:14
@stax76 @luigi311 
Thank you for the feedback and resources.

**To summarize:** 
- need a short names exe -- > please feel free to suggest one keeping in mind that we have svt-hevc / svt-av1 (encoder and decoder) / svt-vp9 
- need better documentation for cli params matching cfg files -- > Agreed <WIP>
- long version and short version cli -- > Agreed 
- y4m -- > supported

We have just finished implementing the last set of av1 features for the encoder. We will be working on both a better documentation for the cli and for the libraries them selves. That said, this is an open source project and as much as feedback is welcomed and appreciated, contributions are even more welcomed.

**Comment by luigi311** [comment] 2020-01-12 04:07
Man the way you guys handled parsing inputs is massive. If solution 1 is acceptable i can start to give it a go and try and match the short and long variables to other encoders such as x265. What can not be directly replaced we can start putting down some ideas on this page to see what are acceptable short and long variables. Long variables should be easy but short variables might be challenging.

Solution 1:
This way would consist of duplicating what we have now, instead of a single define for inputs we can possibly have up to 3, TOKEN_SHORT, TOKEN_LONG, TOKEN_LEGACY. Where short will be the single dash short variables, long will be double dashed spelled out variables and legacy would be the existing variables to maintain backwards comparability. To get all the different tokens to work you can do a logical or for all the possible options where they are called. 

Solution 2:
Rewrite the entire parsing to utilize the standard getopt to call the functions that are actually doing the parsing. This solution would probably be best but would consist of a lot more planning and could potentially break anything that is currently modifying the EbAppConfig.c file.

**Comment by hassount** [comment] 2020-06-18 19:00
closing this after merging the PRs above, @luigi311 please open a new issue with any further discussion about this if need be. A reminder that contributions are quite welcome on this as the team is focused on the trade-off optimization of the library rather than the CLI which we believe is quite usable at this point.

**Closed by hassount** 2020-06-18 19:00 UTC
Labels: API Change, documentation, enhancement
