### ISSUE TITLE
Failure unit test case in NNPRED/NNPredTest

### ISSUE THREAD

**Issue by Cidana-Developers** [OpenVisualCloud/SVT-AV1#965] opened 2020-01-17 08:55 UTC
Found new failure test case in NNPRED/NNPredTest
~~~
[----------] 1 test from NNPRED/NNPredTest
[ RUN      ] NNPRED/NNPredTest.NNPredTest/0
/home/travis/build/Cidana-Developers/SVT-AV1/test/EbNNPredictTests.cc:69: Failure
Expected equality of these values:
  ref[i]
    Which is: -811.78
  test[i]
    Which is: -811.779
 Mismatch at index 0 C value: -811.77978515625 SSE3 value: -811.779296875
[  FAILED  ] NNPRED/NNPredTest.NNPredTest/0, where GetParam() = 0x563e43ad4a60 (0 ms)
[----------] 1 test from NNPRED/NNPredTest (0 ms total)
~~~

It is difficult to re-produce for its input data is random in time seed.

**Comment by Cidana-Developers** [comment] 2020-01-17 08:58
https://github.com/OpenVisualCloud/SVT-AV1/blob/ba3dd4480d44d4d772fd0ab942ccc58c56cd3023/test/EbNNPredictTests.cc#L69

This assertion might be changed to **ASSERT_FLOAT_EQ**

**Comment by jryzkns** [comment] 2020-01-18 02:10
Good catch!

> https://github.com/OpenVisualCloud/SVT-AV1/blob/ba3dd4480d44d4d772fd0ab942ccc58c56cd3023/test/EbNNPredictTests.cc#L69
> 
> This assertion might be changed to **ASSERT_FLOAT_EQ**

Agreed, also it seems like ASSERT_NEAR might also be a good choice since there is more control over how close the values can be. In the grand scheme of things this UT fail shouldn't be an issue to the encoder since the outputs are fed to a softmax for classification.

For reference: https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#floating-point-macros

**Comment by xuguangxin** [comment] 2020-01-20 02:50
> It is difficult to re-produce for its input data is random in time seed.
maybe we can make the seed as a member variable of NNPredTest and print out the seed when we find a mismatch. 
So we can reproduce the issue again use the seed.

possible code
```
seed_  = unsigned(time(NULL));
...

ASSERT_EQ(ref[i],test[i])
                << " Mismatch at index " << i
                    << " C value: " << ref[i]
                    << " SSE3 value: " << test[i]<< ", seed is: "<<seed_;

```

**Comment by hassount** [comment] 2020-03-27 15:57
@Cidana-Developers has this issue been resolved ?

**Comment by Cidana-Developers** [comment] 2020-04-01 03:28
> @Cidana-Developers has this issue been resolved ?

this test was removed in PR #1080

**Comment by tszumski** [comment] 2020-07-17 10:52
@ttrigui 
Test was removed in PR #1080, I think that this issue can be closed

**Comment by ttrigui** [comment] 2020-07-17 16:30
> @ttrigui
> Test was removed in PR #1080, I think that this issue can be closed

was the test removed because it was failing? We have to put it back, test it and if it fails we need to fix it.

**Comment by tszumski** [comment] 2020-07-20 04:57
> was the test removed because it was failing? We have to put it back, test it and if it fails we need to fix it.

Kernel ```av1_nn_predict_c``` and its simd version ```av1_nn_predict_sse3``` were unused in code, neither tests or implementation exist any more

**Comment by ttrigui** [comment] 2020-07-20 08:02
> > was the test removed because it was failing? We have to put it back, test it and if it fails we need to fix it.
> 
> Kernel `av1_nn_predict_c` and its simd version `av1_nn_predict_sse3` were unused in code, neither tests or implementation exist any more

I see thanks for the clarification. @hassount I think we can close this issue then?

**Comment by hassount** [comment] 2020-07-20 15:11
> > > was the test removed because it was failing? We have to put it back, test it and if it fails we need to fix it.
> > 
> > 
> > Kernel `av1_nn_predict_c` and its simd version `av1_nn_predict_sse3` were unused in code, neither tests or implementation exist any more
> 
> I see thanks for the clarification. @hassount I think we can close this issue then?

@Cidana-Developers do you agree that this issue should be closed ?

**Comment by Cidana-Developers** [comment] 2020-07-21 03:54
> was the test removed because it was failing? We have to put it back, test it and if it fails we need to fix it.
> 
> Kernel av1_nn_predict_c and its simd version av1_nn_predict_sse3 were unused in code, neither tests or implementation exist any more
> 
> I see thanks for the clarification. @hassount I think we can close this issue then?
> 
> @Cidana-Developers do you agree that this issue should be closed ?

Sure, I agree to close this issue since both the implementation and the tests have been removed.

**Closed** 2020-08-21 06:01 UTC
Labels: bug, simd, test
