### ISSUE TITLE
One frame is written to each IVF packet instead of one temporal unit

### ISSUE THREAD

**Issue by tdaede** [OpenVisualCloud/SVT-AV1#33] opened 2019-02-08 09:42 UTC
Each IVF packet must contain one temporal unit. As a result, svt-av1 playback is currently jittery or broken when using altrefs (the default).

**Comment by moisesmcardona** [comment] 2019-02-10 16:51
This must be what I've been experimenting...

In this thread I have a sample using SVT-AV1 and the same video encoded with rav1e:
https://www.reddit.com/r/AV1/comments/ankpad/svtav1_encode_test_vs_rav1e_test/

**Comment by kylophone** [comment] 2019-02-11 20:11
@hassount, just want to make sure you saw this. Looks like the `ivf` muxer needs help.

**Comment by j-mas** [comment] 2019-02-15 23:56
Please solve this issue! The resulting ivf files are so jerky that they are not usable with the mpv or VLC player, and therefore not usable for me. Many Thanks!

**Comment by hassount** [comment] 2019-02-17 02:05
@j-mas 
ok, we will work on this with a high priority.

**Comment by j-mas** [comment] 2019-02-17 10:33
Thank you!

**Comment by jsunintel** [comment] 2019-02-18 02:14
#33 is closed. Anymore works needed from me?

**Comment by gnafuthegreat** [comment] 2019-02-18 16:11
To clarify, #42 is closed.  This issue (#33) is not yet resolved.  I'll chime in as another person touched by this issue, and I'd also like to say I've seen some confusion on a few different forums with users having issues either with stuttering playback or issues muxing into other containers because of the malformed IVF container.

@hassount Thanks for working on this.

**Comment by EwoutH** [comment] 2019-02-20 15:05
@hassount @jsunintel Any progress update?

**Comment by hassount** [comment] 2019-02-20 17:51
Working on it, found the problem and working on a fix that works with the API design.

**Comment by hassount** [comment] 2019-02-22 22:31
#107

**Comment by j-mas** [comment] 2019-02-22 23:39
For me it now works! No longer jerky!
Thank you!

**Comment by j-mas** [comment] 2019-02-24 00:28
With the newest build in AppVeyor it is jerky and chubby again! The Problem is not solved!

**Comment by hassount** [comment] 2019-02-24 21:04
@j-mas you mean from the master ? #107 is not merged yet. Please let me know if you're seeing it from the PR build

**Comment by j-mas** [comment] 2019-02-25 22:01
@hassount yes I mean from the master.

**Comment by tnti** [comment] 2019-02-26 04:49
@hassount 
 Fast forward will cause problems with the search for keyframes. hassount
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000021240219fc0] seek_frame_generic failed as this stream seems to contain no keyframes after the target timestamp, 1002 non keyframes found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000021240219fc0] seek_frame_generic failed as this stream seems to contain no keyframes after the target timestamp, 1002 non keyframes found
E:\Gotoubun no Hanayome\Gotoubun no Hanayome 06 1080p - [0] Japanese_muxed.mp4: error while seeking
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000021240219fc0] seek_frame_generic failed as this stream seems to contain no keyframes after the target timestamp, 1002 non keyframes found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000021240219fc0] seek_frame_generic failed as this stream seems to contain no keyframes after the target timestamp, 1002 non keyframes found
E:\Gotoubun no Hanayome\Gotoubun no Hanayome 06 1080p - [0] Japanese_muxed.mp4: error while seeking
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000021240219fc0] seek_frame_generic failed as this stream seems to contain no keyframes after the target timestamp, 1002 non keyframes found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000021240219fc0] seek_frame_generic failed as this stream seems to contain no keyframes after the target timestamp, 1002 non keyframes found
E:\Gotoubun no Hanayome\Gotoubun no Hanayome 06 1080p - [0] Japanese_muxed.mp4: error while seeking
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000021240219fc0] seek_frame_generic failed as this stream seems to contain no keyframes after the target timestamp, 1002 non keyframes found
[libaom-av1 @ 0000021244f62e00] Failed to decode frame: Corrupt frame detected
[libaom-av1 @ 0000021244f62e00]   Additional information: Failed to decode tile data
[libaom-av1 @ 0000021244f62e00] Failed to decode frame: Corrupt frame detected
[libaom-av1 @ 0000021244f62e00]   Additional information: Keyframe / intra-only frame required to reset decoder state
[libaom-av1 @ 0000021244f62e00] Failed to decode frame: Corrupt frame detected
[libaom-av1 @ 0000021244f62e00]   Additional information: Keyframe / intra-only frame required to reset decoder state
[libaom-av1 @ 0000021244f62e00] Failed to decode frame: Corrupt frame detected
[libaom-av1 @ 0000021244f62e00]   Additional information: Keyframe / intra-only frame required to reset decoder state
[libaom-av1 @ 0000021244f62e00] Failed to decode frame: Corrupt frame detected
[libaom-av1 @ 0000021244f62e00]   Additional information: Keyframe / intra-only frame required to reset decoder state
[libaom-av1 @ 0000021244f62e00] Failed to decode frame: Corrupt frame detected
[libaom-av1 @ 0000021244f62e00]   Additional information: Keyframe / intra-only frame required to reset decoder state
[libaom-av1 @ 0000021244f62e00] Failed to decode frame: Corrupt frame detected
[libaom-av1 @ 0000021244f62e00]   Additional information: Keyframe / intra-only frame required to reset decoder state
[libaom-av1 @ 0000021244f62e00] Failed to decode frame: Corrupt frame detected
[libaom-av1 @ 0000021244f62e00]   Additional information: Keyframe / intra-only frame required to reset decoder state
[libaom-av1 @ 0000021244f62e00] Failed to decode frame: Corrupt frame detected
[libaom-av1 @ 0000021244f62e00]   Additional information: Keyframe / intra-only frame required to reset decoder state
[libaom-av1 @ 0000021244f62e00] Failed to decode frame: Corrupt frame detected
[libaom-av1 @ 0000021244f62e00]   Additional information: Keyframe / intra-only frame required to reset decoder state
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000021240219fc0] seek_frame_generic failed as this stream seems to contain no keyframes after the target timestamp, 1002 non keyframes found
E:\Gotoubun no Hanayome\Gotoubun no Hanayome 06 1080p - [0] Japanese_muxed.mp4: error while seeking
[libaom-av1 @ 0000021244f62e00] Failed to decode frame: Corrupt frame detected

**Comment by hassount** [comment] 2019-02-28 18:32
Can we check this on the latest master ?

**Comment by tnti** [comment] 2019-02-28 19:30
error message.
ffplay version N-93264-g85051febc6 Copyright (c) 2003-2019 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20190212
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 26.100 / 56. 26.100
  libavcodec     58. 47.102 / 58. 47.102
  libavformat    58. 26.101 / 58. 26.101
  libavdevice    58.  6.101 / 58.  6.101
  libavfilter     7. 48.100 /  7. 48.100
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
[libaom-av1 @ 0000021da89ad100] 1.0.0-1369-gcde3872bd    0B f=0/0
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\TNTI\Downloads\1.mp4_SVT-AV1_muxed.mp4':
  Metadata:
    major_brand     : iso4
    minor_version   : 1
    compatible_brands: iso4av01
    creation_time   : 2019-02-28T19:25:53.000000Z
  Duration: 00:01:52.20, start: 0.000000, bitrate: 2707 kb/s
    Stream #0:0(und): Video: av1 (Main) (av01 / 0x31307661), yuv420p(tv), 1280x720, 2565 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 24k tbc (default)
    Metadata:
      creation_time   : 2019-02-28T19:25:53.000000Z
    Stream #0:1(jpn): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 174 kb/s (default)
    Metadata:
      creation_time   : 2019-02-28T19:25:53.000000Z
[libaom-av1 @ 0000021da89ed4c0] 1.0.0-1369-gcde3872bd
libpng warning: iCCP: known incorrect sRGB profilesq=    0B f=0/0
libpng warning: iCCP: known incorrect sRGB profilesq=    0B f=0/0
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000021da899a000] seek_frame_generic failed as this stream seems to contain no keyframes after the target timestamp, 1002 non keyframes found
    Last message repeated 1 times
C:\Users\TNTI\Downloads\1.mp4_SVT-AV1_muxed.mp4: error while seeking
C:\Users\TNTI\Downloads\1.mp4_SVT-AV1_muxed.mp4: error while seeking

**Comment by hassount** [comment] 2019-02-28 19:41
@tnti 
Can you please test with ffmpeg 4.1.1 ?

**Comment by tnti** [comment] 2019-02-28 19:44
https://ffmpeg.zeranoe.com/builds/
20190227-85051fe 
Play the video using ffplay.

**Comment by hassount** [comment] 2019-02-28 20:34
Downloaded t the new build and ran it on the stream and I see no issues. used commit 04f8e2d873fe7938e1c0558d92010e6db61ae73d from the master, can you please confirm that you used the right build ? otherwise, could you please share the command line, maybe there's a bug you're triggering

**Comment by tnti** [comment] 2019-02-28 20:42
Example command line:
"D:\Encoder\FFMPEG\ffmpeg.exe" -loglevel level+error -i "%~dpn1.mp4" -strict -1 -f rawvideo -nostdin - | "D:\Encoder\SVT-AV1\SvtAv1EncApp" -i stdin -enc-mode 3 -w 1280 -h 720 -bit-depth 8 -fps-num 30000 -fps-denom 1001 -hierarchical-levels 4 -intra-period 240 -irefresh-type 1 -q 28 -rc 0 -n 2690 -b "%~dpn1_SVT-AV1.ivf"

**Comment by EwoutH** [comment] 2019-03-06 00:52
Is this still a thing? I just encoded a .y4m on the latest master and the .ivf played back fine on VLC, mpv and ffplay.

**Comment by tnti** [comment] 2019-03-06 01:11
There is still no key frame.

[libaom-av1 @ 00000210ffec5b40] 1.0.0-1369-gcde3872bd
libpng warning: iCCP: known incorrect sRGB profilesq=    0B f=0/0
[ivf @ 00000210ffe8a480] seek_frame_generic failed as this stream seems to contain no keyframes after the target timestamp, 1002 non keyframes found
[ivf @ 00000210ffe8a480] seek_frame_generic failed as this stream seems to contain no keyframes after the target timestamp, 1002 non keyframes found
E:\Gotoubun no Hanayome\Gotoubun no Hanayome 08 1080p.mkv_SVT-AV1.ivf: error while seeking
[ivf @ 00000210ffe8a480] seek_frame_generic failed as this stream seems to contain no keyframes after the target timestamp, 1002 non keyframes found
    Last message repeated 1 times
E:\Gotoubun no Hanayome\Gotoubun no Hanayome 08 1080p.mkv_SVT-AV1.ivf: error while seeking
[ivf @ 00000210ffe8a480] seek_frame_generic failed as this stream seems to contain no keyframes after the target timestamp, 1002 non keyframes found
    Last message repeated 1 times
E:\Gotoubun no Hanayome\Gotoubun no Hanayome 08 1080p.mkv_SVT-AV1.ivf: error while seeking
[ivf @ 00000210ffe8a480] seek_frame_generic failed as this stream seems to contain no keyframes after the target timestamp, 1002 non keyframes found
    Last message repeated 1 times
E:\Gotoubun no Hanayome\Gotoubun no Hanayome 08 1080p.mkv_SVT-AV1.ivf: error while seeking
[ivf @ 00000210ffe8a480] seek_frame_generic failed as this stream seems to contain no keyframes after the target timestamp, 1002 non keyframes found
    Last message repeated 1 times
E:\Gotoubun no Hanayome\Gotoubun no Hanayome 08 1080p.mkv_SVT-AV1.ivf: error while seeking
[ivf @ 00000210ffe8a480] seek_frame_generic failed as this stream seems to contain no keyframes after the target timestamp, 1002 non keyframes found
    Last message repeated 1 times
E:\Gotoubun no Hanayome\Gotoubun no Hanayome 08 1080p.mkv_SVT-AV1.ivf: error while seeking
[libaom-av1 @ 00000210ffec5b40] Failed to decode frame: Corrupt frame detected
[libaom-av1 @ 00000210ffec5b40]   Additional information: Failed to decode tile data
[libaom-av1 @ 00000210ffec5b40] Failed to decode frame: Corrupt frame detected
[libaom-av1 @ 00000210ffec5b40]   Additional information: Keyframe / intra-only frame required to reset decoder state
[ivf @ 00000210ffe8a480] seek_frame_generic failed as this stream seems to contain no keyframes after the target timestamp, 1002 non keyframes found
    Last message repeated 1 times
E:\Gotoubun no Hanayome\Gotoubun no Hanayome 08 1080p.mkv_SVT-AV1.ivf: error while seeking
[ivf @ 00000210ffe8a480] seek_frame_generic failed as this stream seems to contain no keyframes after the target timestamp, 1002 non keyframes found
    Last message repeated 1 times
E:\Gotoubun no Hanayome\Gotoubun no Hanayome 08 1080p.mkv_SVT-AV1.ivf: error while seeking
[ivf @ 00000210ffe8a480] seek_frame_generic failed as this stream seems to contain no keyframes after the target timestamp, 1002 non keyframes found
    Last message repeated 1 times
E:\Gotoubun no Hanayome\Gotoubun no Hanayome 08 1080p.mkv_SVT-AV1.ivf: error while seeking
[ivf @ 00000210ffe8a480] seek_frame_generic failed as this stream seems to contain no keyframes after the target timestamp, 1002 non keyframes found
[ivf @ 00000210ffe8a480] seek_frame_generic failed as this stream seems to contain no keyframes after the target timestamp, 1002 non keyframes found
E:\Gotoubun no Hanayome\Gotoubun no Hanayome 08 1080p.mkv_SVT-AV1.ivf: error while seeking

**Comment by jbeich** [comment] 2019-03-06 12:03
@tnti, how old is your FFmpeg version? AV1 parser was added in `n4.1`, required to set keyframes. I have no issues remuxing IVF->MP4 via FFmpeg `n4.1.1`.

**Comment by tnti** [comment] 2019-03-13 09:57
@EwoutH  @hassount 
There may be a problem with the splitter's support for CRA.
Previously, CRA in HEVC had similar problems.
When I use the IDR mode, I can find the keyframes correctly.

**Closed** 2020-02-24 05:42 UTC
Labels: bug
