### ISSUE TITLE
allocate memory failed

### ISSUE THREAD

**Issue by n808** [OpenVisualCloud/SVT-AV1#656] opened 2019-09-27 14:07 UTC
This error message appears every time, yet encoding continues:
allocate memory failed, at path/git/SVT-AV1/Source/Lib/Common/Codec/RateControlModel.c, L86
Example cmd line to repro: "ffmpeg -loglevel verbose -y  -i "Sintel_1080p.mp4" -r 2402400/100000 -threads 10 -t 10.000000  -map v:0   -pix_fmt yuv420p  -f yuv4mpegpipe - 2> "ffmpeg.log" | SvtAv1EncApp -i stdin -bit-depth 8 -scd 1 -nb -1 -enc-mode 8 -intra-period 31 -lad 31 -fps-num 2402400 -fps-denom 100000 -rc 0 -q 26 -stat-report 1 -stat-file av1stats.log -b enc_video.ivf"

 *-cpu:0
       description: CPU
       product: Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz
       vendor: Intel Corp.
       vendor_id: GenuineIntel
       physical id: a2
       bus info: cpu@0
       version: Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz
       slot: SOCKET 1
       size: 1396MHz
       capacity: 4GHz
       width: 64 bits
       clock: 100MHz
       capabilities: lm fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp x86-64 constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm epb intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc dtherm ida arat pln pts spec_ctrl intel_stibp flush_l1d cpufreq
       configuration: cores=10 enabledcores=10 threads=20
  *-cpu:1 (same as cpu 0)

**Comment by n808** [comment] 2019-09-27 14:16
I realize now that this problem occurs because argument -n <number of frames> is missing. If I add this number, calculated to match the number of frames corresponding to -t <time> argument to ffmpeg, everything works. I will adjust my workflow correspondingly. 

Feel free to close this issue as needed.

**Comment by Fuchs4** [comment] 2019-09-27 16:59
> Feel free to close this issue as needed.

I disagree. I encountered this issue as well, and it definitively didn't exist a few weeks ago. In my opinion the encoder shouldn't require the -n argument. Gathering the number of frames for an arbitrary video can be very time consuming, and is impossible when streaming.

I compiled it with makepkg in manjaro linux and makepkg gave me the following warning:
`WARNUNG: Paket enthält einen Verweis auf $srcdir
usr/lib/libSvtAv1Enc.so.0.7.0
usr/lib/libSvtAv1Dec.so.0.7.0`
(translates to: WARNING: Package contains a link to $srcdir)

the error message from SvtAv1EncApp:
`allocate memory failed, at /var/tmp/pamac-build-username/svt-av1-git/src/svt-av1/Source/Lib/Common/Codec/RateControlModel.c, L86`

`pamac-build-username` is a temporary directory that got automatically deleted after compilation has finished, so the referenced file does not exist in my filesystem. I don't know almost nothing about programming or compiling C, but I am sure the binary shouldn't use files from the directory containing the source code.

**Comment by rubenmt94** [comment] 2020-01-24 11:38
When I try to encode 4k videos (3840x2160) something similar happens, I get the following error: allocate memory failed, at C: \ Users \ user \ Documents \ SVT-AV1-master \ Source \ Lib \ Encoder \ Codec \ EbPictureControlSet.c, L400
Could not allocate enough memory for channel 1
Encoder finished

However, when I encode videos of HD quality or lower, no problem occurs and the encoding is successful. Does anyone know what the problem is?

**Comment by hassount** [comment] 2020-01-31 19:51
@rubenmt94 
how much RAM do you have on your system ?

**Comment by hassount** [comment] 2020-03-27 16:10
closing as this is not reproducible.

**Closed by hassount** 2020-03-27 16:10 UTC
