### ISSUE TITLE
Crash after 1 frame on -enc-mode 1

### ISSUE THREAD

**Issue by EwoutH** [OpenVisualCloud/SVT-AV1#99] opened 2019-02-22 09:23 UTC
`-enc-mode 1` crashes on both 425ba777 and 16375676. All other encoder modes work fine.

- **Video:** Morocco (1080p 8-bit 4:2:0)
- **Settings:** ` -enc-mode 1 -n 120`
- **System:** i5-4590 (4c/4t, AVX2), 16GB DDR3, Windows 10 64-bit

```
Microsoft Windows [Version 10.0.17763.316]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\ewout_000>echo %time%
10:17:54,70

C:\Users\ewout_000>SVT-AV1-05\SvtAv1EncApp -i "E:\Morocco8K-8b-1920.y4m" -enc-mode 1 -n 120 -b Morocco-SVT-05-m1.ivf
-------------------------------------------
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.4.0
SVT [build]  :  Visual Studio 2017 64 bit
LIB Build date: Feb 22 2019 03:28:14
-------------------------------------------
Number of logical cores available: 4
Number of PPCS 73
-------------------------------------------
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 1
SVT [config]: EncoderBitDepth / CompressedTenBitFormat                          : 8 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 1920 / 1080
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 19001 / 317 / 64 / 1
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 4 / 0 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 50 / 33 / 0
-------------------------------------------
Encoding         1
C:\Users\ewout_000>echo %time%
10:18:18,38

C:\Users\ewout_000>SVT-AV1-06\SvtAv1EncApp -i "E:\Morocco8K-8b-1920.y4m" -enc-mode 1 -n 120 -b Morocco-SVT-06-m1.ivf
-------------------------------------------
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.4.0
SVT [build]  :  Visual Studio 2017 64 bit
LIB Build date: Feb 22 2019 00:35:28
-------------------------------------------
Number of logical cores available: 4
Number of PPCS 73
-------------------------------------------
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 1
SVT [config]: EncoderBitDepth / CompressedTenBitFormat                          : 8 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 1920 / 1080
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 19001 / 317 / 64 / 1
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 4 / 0 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 50 / 33 / 0
-------------------------------------------
Encoding         1
C:\Users\ewout_000>echo %time%
10:18:43,99
```

**Comment by jbeich** [comment] 2019-02-22 11:07
Similar to #102. Can be worked around by removing
https://github.com/OpenVisualCloud/SVT-AV1/blob/425ba7775b84c0177f0ffd576faea4ed7314af94/Source/Lib/Codec/EbDefinitions.h#L151

**Comment by hassount** [comment] 2019-02-22 22:39
This seems to be a duplicate of #102

**Comment by jbeich** [comment] 2019-02-23 05:52
@EwoutH, can you reproduce with todays build (2c6f550 or later)? If not close.

**Comment by EwoutH** [comment] 2019-02-23 11:04
@jbeich Works great and can be closed! :)

**Closed** 2019-02-23 11:05 UTC
Labels: bug
