### ISSUE TITLE
r2r mismatch when overlay is enabled

### ISSUE THREAD

**Issue by mtangtencent** [OpenVisualCloud/SVT-AV1#929] opened 2019-12-30 20:52 UTC
I was testing the option `enable-overlays` and found r2r mismatch (both release and debug have this issue) using the following command line.
./SvtAv1EncApp.exe -i BasketballDrill_832x480_50.yuv -w 832 -h 480 -b test.ivf -enc-mode 8 -n 200 -rc 0 -q 24 -intra-period 31 -fps-num 50 -fps-denom 1 -enable-overlays 1

The version of SVT-AV1 I used was v0.8.0 (af16f709)

**Comment by AlexBoswellVCD** [comment] 2019-12-31 19:46
I was able to also reproduce this in ( 57bd982 )

**Comment by kelvinhu325** [comment] 2020-02-20 03:39
The picture POC112 is set to is_alt_ref=1, and this picture happens r2r in generated bitstream, did not find root cause yet.

**Comment by hassount** [comment] 2020-03-19 22:09
@mtangtencent can you please check if #1145 addressed your test case?

**Comment by MinhaoTang** [comment] 2020-03-20 02:01
@hassount It fixed the r2r when overlay is enabled. But it reports "bug, too many frames in undisplayed queue" when I used "./SvtAv1EncApp.exe -i BasketballDrill_832x480_50.yuv -w 832 -h 480 -b test.ivf -enc-mode 8 -n 200 -rc 0 -q 24 -intra-period 31 -fps-num 50 -fps-denom 1 -enable-overlays 1"

**Comment by mtangtencent** [comment] 2020-03-20 02:07
@hassount It fixed the r2r when overlay is enabled. But it reports "bug, too many frames in undisplayed queue" when I used "./SvtAv1EncApp.exe -i BasketballDrill_832x480_50.yuv -w 832 -h 480 -b test.ivf -enc-mode 8 -n 200 -rc 0 -q 24 -intra-period 31 -fps-num 50 -fps-denom 1 -enable-overlays 1"

**Comment by kelvinhu325** [comment] 2020-03-20 02:38
> @hassount It fixed the r2r when overlay is enabled. But it reports "bug, too many frames in undisplayed queue" when I used "./SvtAv1EncApp.exe -i BasketballDrill_832x480_50.yuv -w 832 -h 480 -b test.ivf -enc-mode 8 -n 200 -rc 0 -q 24 -intra-period 31 -fps-num 50 -fps-denom 1 -enable-overlays 1"

Hi @mtangtencent , is this "bug, too many frames in undisplayed queue" also reported without thi fixing change?

**Comment by mtangtencent** [comment] 2020-03-20 02:57
@kelvinhu325 Actually I cannot verify it. I was using master at a29d766d, which encounters segfault when I used ./SvtAv1EncApp.exe -i BasketballDrill_832x480_50.yuv -w 832 -h 480 -b test.ivf -enc-mode 8 -n 200 -rc 0 -q 24 -intra-period 31 -fps-num 50 -fps-denom 1 -enable-overlays 1

**Comment by kelvinhu325** [comment] 2020-03-20 07:43
Hi @mtangtencent , I tried to run it on Linux at  a29d766, it does not get segfault, could you try it on Linux too? if it also gets error, it's not r2r issue, maybe we can debug it further in a new bug, supposed my change does not cause this undisplayed queue issue because I did not add any displayed queue change.

**Comment by hassount** [comment] 2020-03-20 20:22
"bug, too many frames in undisplayed queue"

@xuguangxin 
Are you familiar with the error above ?

**Comment by xuguangxin** [comment] 2020-03-23 04:34
We use a queue to hold all undisplayed frames. When we got a show existing frame, we will pick one frame from the queue for output, the frame will have the lowest pts. 

The queue size is REF_FRAMES. It should enough for our case. Unless we hold too many undisplayed frames and we do not have show existing frame.

**Comment by xuguangxin** [comment] 2020-03-23 07:17
@hassount & @kelvinhu325 even I double the size of undisplayed queue, it still gets the same error. I need more time to check the overlay display mechanism.

**Comment by xuguangxin** [comment] 2020-03-23 09:09
the "bug, too many frames in undisplayed queue" issue will be fixed by https://github.com/OpenVisualCloud/SVT-AV1/pull/1151.
I believe the issue is introduced by https://github.com/OpenVisualCloud/SVT-AV1/commit/dd72a78720964c9d7e3bb6b2254bf6069b640c01. @Cidana-Developers , could you check why it's not caught by the unit test?

thanks

**Closed** 2020-03-26 23:25 UTC
Labels: bug
