### ISSUE TITLE
Crash with -enc-mode 1 at ~ 450 frames

### ISSUE THREAD

**Issue by JouMxyzptlk** [OpenVisualCloud/SVT-AV1#1159] opened 2020-03-29 11:38 UTC
OS: Win10 x64. CPU: Ryzen 3900x. RAM 64 GB ECC. More hardware details if you follow the second link.
Source video: https://joumxyzptlk.de/tmp/svt-av1-0.8.1-bug/svt-0.8.1-input-video.7z
Fail result (with a bit more log): https://joumxyzptlk.de/tmp/svt-av1-0.8.1-bug/svt-0.8.1-encoding-fail.zip
For comparison: -enc-mode 2 and q40: https://joumxyzptlk.de/tmp/svt-av1-0.8.1-bug/svt-0.8.1-encoding-works.zip

Exact command line: 
`C:\tmp>c:\prog\svt-av1\SvtAv1EncApp.exe -i input.yuv420p -n 5038 -rc 0 -q 42 -lp 24 -enc-mode 1 -tile-rows 1 -tile-columns 2 -lad 80 -b out.ivf`

Output:
```
-------------------------------------------
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.8.1
SVT [build]  :  Visual Studio 2017 64 bit
LIB Build date: Jan 29 2020 14:56:28
-------------------------------------------
Number of logical cores available: 24
Number of PPCS 88
[asm level on system : up to avx2]
[asm level selected : up to avx2]
-------------------------------------------
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 1
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 1920 / 1080
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 500 / 21 / 16 / 1
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 4 / 0 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 42 / 33 / 0
-------------------------------------------
Encoding       451
C:\tmp>
```

Eventlog:
```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-03-28T13:40:09.693749300Z" /> 
  <EventRecordID>16542</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>PC-JOU</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>SvtAv1EncApp.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5e319d54</Data> 
  <Data>SvtAv1Enc.dll</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5e319d25</Data> 
  <Data>c0000005</Data> 
  <Data>000000000005b9b5</Data> 
  <Data>455c</Data> 
  <Data>01d605028efd0123</Data> 
  <Data>c:\prog\svt-av1\SvtAv1EncApp.exe</Data> 
  <Data>c:\prog\svt-av1\SvtAv1Enc.dll</Data> 
  <Data>47813dc8-7e73-4ee9-8a73-fb94e43e41a4</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

If you think I should test with a specific setting, just say.
I've already encoded 30+ videos with SVT-AVT with similar settings (-end-mode 1 / 2, Q40 Q42 Q45), including a 4k 105 Minute movie which took two and a half weeks in -enc-mode 2 (i.e. the machine is considered stable). Extreme conservative RAM and CPU settings were tried as well to rule that out.

**Comment by JouMxyzptlk** [comment] 2020-03-29 11:41
PS: Thank you for that encoder.
If only it would use Intel Ivy-Bridge Level SSE4.2+AVX. It switches to "asm level c" only and is unbearable slow there ;)

**Comment by mazharaIntel** [comment] 2020-03-31 20:35
The issue has been reproduced with the clip and command line provided. It has been to global_motion. Disabling compute_global_motion in M1 causes no error.

**Comment by JouMxyzptlk** [comment] 2020-03-31 20:48
Thank you for confirming. Does this mean: Will be fixed with next version?

**Comment by mazharaIntel** [comment] 2020-03-31 21:30
@JouMxyzptlk Still debugging to figure out a fix for this.

**Comment by mazharaIntel** [comment] 2020-04-03 21:02
The buffer size of ref_pic->buffer_y is less than the memory accessed during a read operation. The next thing to look into is the offset set during the read operation.

**Comment by ttrigui** [comment] 2020-04-08 21:14
@magwyz the crash is caused by GM mvs going out of boundaries.
The Gm Mvs are used to fill in mvp table. Can you please make sure that the MV derivation is properly done?
    const int xc = (mat[2] - (1 << WARPEDMODEL_PREC_BITS)) * x + mat[3] * y + mat[0];
    const int yc = mat[4] * x + (mat[5] - (1 << WARPEDMODEL_PREC_BITS)) * y + mat[1];
If you want to reproduce this issue you can use work_on_Issue_1159 branch and use -enc-mode 4 to make it fast.

**Comment by magwyz** [comment] 2020-04-14 14:28
@ttrigui I was able to reproduce the issue but not able to fix it. The crash may come from the motion vector prediction (`generate_av1_mvp_table`) but I do not know very well this part.

The bitstream corruption still happens when the injection of global motion candidates is disabled in `EbModeDecision.c`. However, it does not happen in `-enc-mode 5` that also generates and writes the global motion parameters in the bitstream. So, the clamping of the global motion parameters is probably done right.

Unfortunately, I will not be able to investigate more since my time at Videolabs has ended. They have however been informed of the issue.

**Comment by hassount** [comment] 2020-04-15 15:12
> @ttrigui I was able to reproduce the issue but not able to fix it. The crash may come from the motion vector prediction (`generate_av1_mvp_table`) but I do not know very well this part.
> 
> The bitstream corruption still happens in `-enc-mode 4` when the injection of global motion candidates is disabled in `EbModeDecision.c`. However, it does not happen in `-enc-mode 5` that also generates and writes the global motion parameters in the bitstream. So, the clamping of the global motion parameters is probably done right.

@magwyz thnx for the feedback and good luck with your future work. 
@jbkempf  FYI

**Comment by jbkempf** [comment] 2020-04-15 15:22
Any stacktrace?

**Comment by hassount** [comment] 2020-04-17 23:35
seems like this is not reproducible anymore in the current master @JouMxyzptlk can you confirm ?

**Comment by JouMxyzptlk** [comment] 2020-04-18 00:58
@hassount I don't have the compile environment. My coding-with-compiling days are too far away (pre 2005) to quickly set it up the way needed, I am mostly scripting today. If you have a windows binary to test for me I'll gladly do.

**Comment by 1480c1** [comment] 2020-04-18 01:05
> If you have a windows binary to test for me I'll gladly do.

https://ci.appveyor.com/project/OpenVisualCloud/svt-av1/builds/32264583/job/oq9qj0hpnc5mttei/artifacts

Here's a link to a commit in the master branch that's ready atm.

**Comment by JouMxyzptlk** [comment] 2020-04-18 01:45
> > If you have a windows binary to test for me I'll gladly do.
> 
> https://ci.appveyor.com/project/OpenVisualCloud/svt-av1/builds/32264583/job/oq9qj0hpnc5mttei/artifacts
> 
> Here's a link to a commit in the master branch that's ready atm.

Sadly no change, still crash around the 450 frames mark with --enc-mode 1, no matter whether q40 or q42.

Q40 test:
`C:\tmp>c:\prog\svt-av1\SvtAv1EncApp.exe -i input.yuv420p -n 5038 -rc 0 -q 40 -lp 24 -enc-mode 1 -tile-rows 1 -tile-columns 2 -lad 80 -b out.ivf`

```
-------------------------------------------
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.8.1
SVT [build]  :  Visual Studio 2019 64 bit
LIB Build date: Apr 18 2020 00:40:23
-------------------------------------------
Number of logical cores available: 24
Number of PPCS 88
[asm level on system : up to avx2]
[asm level selected : up to avx2]
-------------------------------------------
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 1
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 1920 / 1080
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 500 / 21 / 16 / 1
SVT [config]: HierarchicalLevels  / PredStructure               : 4 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 40 / 33 / 0
-------------------------------------------
warning: -enc-mode will be deprecated soon, please use --preset
warning: -tile-rows will be deprecated soon, please use --tile-rows
warning: -tile-columns will be deprecated soon, please use --tile-columns
warning: -rc will be deprecated soon, please use --rc
warning: -lad will be deprecated soon, please use --lookahead
warning: -lp will be deprecated soon, please use --lp
Encoding       457
C:\tmp>
```

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-04-18T01:25:10.030781000Z" /> 
  <EventRecordID>19892</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>PC-JOU</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>SvtAv1EncApp.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5e9a4cb4</Data> 
  <Data>SvtAv1Enc.dll</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5e9a4c82</Data> 
  <Data>c0000005</Data> 
  <Data>00000000000b4135</Data> 
  <Data>3300</Data> 
  <Data>01d6151e976a13a0</Data> 
  <Data>c:\prog\svt-av1\SvtAv1EncApp.exe</Data> 
  <Data>c:\prog\svt-av1\SvtAv1Enc.dll</Data> 
  <Data>ed3acd7c-d291-4064-991b-ea42f6e1d102</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```
Q42 test:
`C:\tmp>c:\prog\svt-av1\SvtAv1EncApp.exe -i input.yuv420p -n 5038 -rc 0 -q 42 -lp 24 -enc-mode 1 -tile-rows 1 -tile-columns 2 -lad 80 -b out.ivf`

```
-------------------------------------------
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.8.1
SVT [build]  :  Visual Studio 2019 64 bit
LIB Build date: Apr 18 2020 00:40:23
-------------------------------------------
Number of logical cores available: 24
Number of PPCS 88
[asm level on system : up to avx2]
[asm level selected : up to avx2]
-------------------------------------------
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 1
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 1920 / 1080
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 500 / 21 / 16 / 1
SVT [config]: HierarchicalLevels  / PredStructure               : 4 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 42 / 33 / 0
-------------------------------------------
warning: -enc-mode will be deprecated soon, please use --preset
warning: -tile-rows will be deprecated soon, please use --tile-rows
warning: -tile-columns will be deprecated soon, please use --tile-columns
warning: -rc will be deprecated soon, please use --rc
warning: -lad will be deprecated soon, please use --lookahead
warning: -lp will be deprecated soon, please use --lp
Encoding       455
C:\tmp>
```

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-04-18T01:42:59.735989900Z" /> 
  <EventRecordID>19895</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>PC-JOU</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>SvtAv1EncApp.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5e9a4cb4</Data> 
  <Data>SvtAv1Enc.dll</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5e9a4c82</Data> 
  <Data>c0000005</Data> 
  <Data>00000000000b4135</Data> 
  <Data>99c</Data> 
  <Data>01d6152123061d24</Data> 
  <Data>c:\prog\svt-av1\SvtAv1EncApp.exe</Data> 
  <Data>c:\prog\svt-av1\SvtAv1Enc.dll</Data> 
  <Data>75b17a5e-04f7-4d27-8961-244f8f345730</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

**Comment by hassount** [comment] 2020-04-18 02:26
@JouMxyzptlk thank you for the help
@OmranAbdelkafi can we check this again to make sure we can reproduce the issue on our side ?

**Comment by mazharaIntel** [comment] 2020-04-20 18:16
It is reproducible with the latest mater 301d535.

**Comment by hassount** [comment] 2020-04-22 06:36
can we retest this to validate #1242 
windows binaries can be found here: https://ci.appveyor.com/project/tianjunwork/svt-av1/builds/32348717/job/psa3ftvfn97vmsc2/artifacts

**Comment by JouMxyzptlk** [comment] 2020-04-22 08:36
> 
> 
> can we retest this to validate #1242
> windows binaries can be found here: https://ci.appveyor.com/project/tianjunwork/svt-av1/builds/32348717/job/psa3ftvfn97vmsc2/artifacts

That build works, no crash! Thank you!
I hope I have such a nice reproducible example for my next bug report, 'cause I will keep on using/testing SVT-AV1.

**Comment by JouMxyzptlk** [comment] 2020-04-22 16:47
Question: Is that fix included in the normal 0.8.2 release? As far as I can see: No ?

**Comment by JouMxyzptlk** [comment] 2020-04-22 20:24
Hold it, it is NOT fixed.
Version 0.8.2 (bot official and this build) generate MUCH smaller video files with --qp 42 than ever before. Showing a visible difference to 0.8.1 -q 42 quality. Do compensate that I adjusted --qp to 35, and it crashes again at about the same place.
Command line used (same video as ever):
`SvtAv1EncApp.exe --input input.yuv420p --frames 5038 --rc 0 --qp 35 --lp 24 --preset 1 --tile-rows 1 --tile-columns 2 --lookahead 80 --output out.ivf`

Output:
```
-------------------------------------------
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.8.2-5-g7e4fba39-dirty
SVT [build]  :  Visual Studio 2019 64 bit
LIB Build date: Apr 22 2020 01:44:18
-------------------------------------------
Number of logical cores available: 24
Number of PPCS 88
[asm level on system : up to avx2]
[asm level selected : up to avx2]
-------------------------------------------
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 1
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 1920 / 1080
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 500 / 21 / 16 / 1
SVT [config]: HierarchicalLevels  / PredStructure               : 4 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 35 / 33 / 0
-------------------------------------------
Encoding       452
```

Eventlog:

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-04-22T19:38:48.133215800Z" /> 
  <EventRecordID>20745</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>PC-JOU</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>SvtAv1EncApp.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5e9fa1ac</Data> 
  <Data>SvtAv1Enc.dll</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5e9fa17c</Data> 
  <Data>c0000005</Data> 
  <Data>00000000000b4000</Data> 
  <Data>3790</Data> 
  <Data>01d618dbbd479884</Data> 
  <Data>c:\prog\svt-av1\SvtAv1EncApp.exe</Data> 
  <Data>c:\prog\svt-av1\SvtAv1Enc.dll</Data> 
  <Data>631cade4-9afd-4311-94ae-f92a98becd47</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

**Comment by lijing0010** [comment] 2020-04-23 02:37
@JouMxyzptlk , you mean the "special" version produces much small size compared to v0.8.2 or v0.8.1?
And I'll try to reproduce the qp35 case, thanks for reporting this.

**Comment by JouMxyzptlk** [comment] 2020-04-23 06:22
I just tested (was late yesterday): official 0.8.2 and https://ci.appveyor.com/project/tianjunwork/svt-av1/builds/32348717/job/psa3ftvfn97vmsc2/artifacts both produce a lot smaller versions. It is like qp rating was changed either by ~10 in absolute, of by ~25% in relative - I didn't check the code about that. It seems like Q 33 0.8.2 is equal to Q 42 0.8.1, but I am still testing to find the new value which satisfies me. The weakness of SVT-AV1 are areas which change color, but brightness only a little so details get smudged.
From the test video at 40 seconds: The see-through wet clothes show it very good. With the new Q 42 interpretation the bra is missing its outline and is generally smudgy while the old Q 42 (end mode 1) gives a "good enough for this anime" result - or for that specific video the old q40 with enc mode 2 due to the crash problem. And yes, it is safe for work since the whole series is her provoking him, but he only wants the sweet marshmallows which she uses.
I can get a lot of other examples, for real humans it is mostly the "looks much younger after encoding" effect I try to avoid, but that one is so easy to spot.

**Comment by silverbacknet** [comment] 2020-04-23 06:50
encmode (preset) 1 got a ton of big changes earlier today, and encmode 0 a few; you might've noticed the speed going down too, as it should be more efficient but slower -- but not the same bitrate, as you've noticed. You could try both https://ci.appveyor.com/project/tianjunwork/svt-av1/builds/32364887 and https://ci.appveyor.com/project/tianjunwork/svt-av1/builds/32365012 to confirm the change happened there. Everything's going to need to be adjusted slightly.

**Comment by JouMxyzptlk** [comment] 2020-04-23 07:04
Slower: Yes, indeed. About whether it needs less bits for the same quality now: Still testing.

**Comment by JouMxyzptlk** [comment] 2020-04-23 07:37
I see: All on https://ci.appveyor.com/project/tianjunwork/svt-av1/history which are based on "master", got builds to download and test.

**Closed** 2020-04-24 03:10 UTC
Labels: bug
