### ISSUE TITLE
Assertion Failed: sign <= 2

### ISSUE THREAD

**Issue by AlexBoswellVCD** [OpenVisualCloud/SVT-AV1#732] opened 2019-10-22 21:36 UTC
I ran SvtAv1EncApp.exe in debug mode with the following command

```
SvtAv1EncApp.exe -enc-mode 0  -w 640  -h 360 -i RAND_640x360p.yuv  -q 46  -fps-num 30000 -fps-denom 1000 -b Release_M0_RAND_640x360p_Q46_3.bin   -n 661  -lad 119  -hdr 0
```

It yields the following error

```
Assertion failed: sign <= 2, file C:\work\RANDclip_debugging\SVT-AV1_ttrigui\SVT-AV1\Source\Lib\Common\Codec\EbEntropyCoding.c, line 451
```

**Comment by hassount** [comment] 2019-10-25 05:41
Seems to be related to #733

**Comment by JacksonDagger** [comment] 2019-11-13 00:56
When I attempted this on the current master I got`Now I got Assertion failed: context_ptr->md_stage_0_count[CAND_CLASS_0] > 0, file \\SVT-AV1\Source\Lib\Common\Codec\EbProductCodingLoop.c`

**Comment by hassount** [comment] 2019-11-19 16:23
can we re-check this ?

**Comment by JacksonDagger** [comment] 2019-11-19 18:20
Now I get `Assertion failed: sign <= 2, file C:\Users\jdagger\Documents\work\19-11-18\SVT-AV1\Source\Lib\Common\Codec\EbEntropyCoding.c, line 409` similar to Alex

**Comment by ttrigui** [comment] 2019-11-19 18:30
> Now I get `Assertion failed: sign <= 2, file C:\Users\jdagger\Documents\work\19-11-18\SVT-AV1\Source\Lib\Common\Codec\EbEntropyCoding.c, line 409` similar to Alex

@JacksonDagger  Can you please test the same thing for https://github.com/OpenVisualCloud/SVT-AV1/tree/R2R_Debug and see if you still get the assertion fail?

**Comment by JacksonDagger** [comment] 2019-11-19 18:45
On R2R_Debug I get`Assertion failed: context_ptr->md_stage_0_count[CAND_CLASS_0] > 0, file C:\Users\jdagger\Documents\work\19-11-18\SVT-AV1\Source\Lib\Common\Codec\EbProductCodingLoop.c, line 7919`

**Comment by hassount** [comment] 2019-11-25 21:59
closing as we don't seem to be reproducing this in master, please reopen if it still exists

**Closed by hassount** 2019-11-25 21:59 UTC
Labels: P1, bug
