### ISSUE TITLE
Crash detected when overlays are enabled (part of the Alt-ref tool)

### ISSUE THREAD

**Issue by mafonsoN** [OpenVisualCloud/SVT-AV1#324] opened 2019-06-03 18:19 UTC
Segfault and deadlocks detected when overlay frames are enabled (-enable-overlays 1) on the current master. This is part of the Alt-ref pictures tool. 

Seems to be caused by conflicts between the memory optimizations (#242) and the Alt-refs.  

Issues are non-deterministic and tend to happen for a small number of sequences/QPs in a single experiment, mostly 360p resolution. Tested on Linux. 

Sample command line in which this issues was reported:

./SvtAv1EncApp -i blue_sky_360p_60f.yuv -w 640 -h 360 -fps-num 60000 -fps-denom 1000 -q 20 -b blue_sky_640x360_60f_svtav1_cq20.ivf -o blue_sky_640x360_60f_svtav1_cq20.yuv -intra-period 119 -bit-depth 8 -enc-mode 0 -n 60 -enable-overlays 1

Call stack of crash:

#0  0x000055a6171cc211 in StationaryEdgeOverUpdateOverTimeLcu (sequence_control_set_ptr=0x55a61b3efcd0,
    totalCheckedPictures=33, picture_control_set_ptr=0x7f6d3e191010, totalLcuCount=60)
    at /root/SVT-AV1-mod/Source/Lib/Common/Codec/EbInitialRateControlProcess.c:668
#1  0x000055a6171cd1a5 in UpdateMotionFieldUniformityOverTime (encode_context_ptr=0x55a61a7b0840,
    sequence_control_set_ptr=0x55a61b3efcd0, picture_control_set_ptr=0x7f6d3e191010)
    at /root/SVT-AV1-mod/Source/Lib/Common/Codec/EbInitialRateControlProcess.c:994
#2  0x000055a6171cf112 in initial_rate_control_kernel (input_ptr=0x55a648fdc7e0)
    at /root/SVT-AV1-mod/Source/Lib/Common/Codec/EbInitialRateControlProcess.c:1784
#3  0x00007f6d4f3be6ba in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#4  0x00007f6d4edeb41d in clone () from /lib/x86_64-linux-gnu/libc.so.6

**Comment by hassount** [comment] 2019-09-19 17:55
@anaghdin 
can we take another look at this ?

**Comment by anaghdin** [comment] 2019-10-04 18:54
@hassount @mafonsoN I was not able to reproduce the problem. Can we get a member of testing team try to reproduce it?

**Comment by hassount** [comment] 2019-10-24 23:59
can not reproduce either, closing the issue, @mafonsoN please reopen if you see this on your end

**Closed by hassount** 2019-10-24 23:59 UTC
Labels: bug
