### ISSUE TITLE
-intra-period causes decoding desync at first refresh point

### ISSUE THREAD

**Issue by rbultje** [OpenVisualCloud/SVT-AV1#386] opened 2019-06-15 13:30 UTC
In any encode, using revision 6fd5646, if I use `-intra-period 120`, I get a decoding desync at frame 121. The output is obviously corrupt when decoding using e.g. FFmpeg (linked to libaom).

Frame 120:
![image](https://user-images.githubusercontent.com/283893/59551996-8cdd1c00-8f4f-11e9-8026-a280b2c74fe0.png)

Frame 121:
![image](https://user-images.githubusercontent.com/283893/59551998-92d2fd00-8f4f-11e9-89da-1469f73017a4.png)

I can see that it inserts an invisible intraonly frame before this, and that one decodes (at least visibly) correctly, but all frames after that do not, be it in libaom, dav1d or FFmpeg (linked against aomdec).

**Comment by rbultje** [comment] 2019-06-15 14:54
I've also noticed this can be worked around by using `-irefresh-type 2`. So it appears only `-irefresh-type 1` is broken.

**Comment by hassount** [comment] 2019-07-05 05:13
Two items to test here in order to box this further:
- Test after the chroma mismatch fix
- Test with -enable-altrefs 0

**Comment by JacksonDagger** [comment] 2019-07-18 23:56
I recreated this and the problem persisted with -enable-altrefs 0

**Comment by chkngit** [comment] 2019-11-07 16:31
@hassount @lijing0010  is this issue related to this PR: Fix non-8 aligned gop size #747 ? 
they both fix RPS I guess

**Comment by JacksonDagger** [comment] 2019-11-08 22:21
@hassount looks like PR #747 fixes it

**Comment by chkngit** [comment] 2019-11-09 00:01
confirmed that this is the same case as the one fixed by #747

**Closed** 2019-11-19 16:22 UTC
Labels: P1, bug
