### ISSUE TITLE
Output to stdout?

### ISSUE THREAD

**Issue by 1480c1** [OpenVisualCloud/SVT-AV1#231] opened 2019-04-23 12:42 UTC
Is there some way to make the encoder output to stdout? something like `-b stdout`? 
That way it can be redirected to some other program to either stream or something similar

**Comment by 1480c1** [comment] 2019-04-23 21:45
I have made it to the point that all of the console output is sent to stderr and stdout is free to be used as an output and it works using -b stdout. \
However, I'm currently trying to see if I can use it in a docker container and although the encode works when not containerized, when I try to redirect the stdout of the container to a file, it somehow gains a kilobyte and is corrupted, so I think somewhere I am messing up

**Comment by kylophone** [comment] 2019-10-18 18:04
Duplicate of #701, I'll close this one for now and we'll track this issue there.

**Closed by kylophone** 2019-10-18 18:04 UTC
Labels: enhancement, question
