### ISSUE TITLE
r2r issue for enc-mode 4

### ISSUE THREAD

**Issue by xuguangxin** [OpenVisualCloud/SVT-AV1#1079] opened 2020-02-24 09:04 UTC
test command line:
../Bin/Release/SvtAv1EncApp -i 1920x1080.y4m -enc-mode 4 -b test.ivf && md5sum test.ivf

you will see md5 is diffrent for every run.

I have test enc-mode 8, it has no such issue.
 I did not test other enc-mode.

**Comment by OmranAbdelkafi** [comment] 2020-02-24 23:32
> test command line:
> ../Bin/Release/SvtAv1EncApp -i 1920x1080.y4m -enc-mode 4 -b test.ivf && md5sum test.ivf
> 
> you will see md5 is diffrent for every run.
> 
> I have test enc-mode 8, it has no such issue.
> I did not test other enc-mode.

Was not able to reproduce the issue ; I have 2 different 1080p clips and performed over 10 runs

**Comment by xuguangxin** [comment] 2020-02-25 01:28
@OmranAbdelkafi thanks for help on this.
I have sent the clip to you through mail.
thanks

**Comment by xuguangxin** [comment] 2020-02-25 06:41
actually we have a similar issue at https://github.com/OpenVisualCloud/SVT-AV1/issues/985
Not sure it's the same problem or not.

**Comment by hassount** [comment] 2020-03-27 16:17
@xuguangxin can you please check if the issue has been resolved in the current master ?

**Comment by xuguangxin** [comment] 2020-03-31 07:06
sure, I will try it later.

**Comment by xuguangxin** [comment] 2020-03-31 11:11
@hassount no lucky. I can still reproduce the issue. md5 mismatch every time for cqp mode.
I have sent the source yuv to @OmranAbdelkafi , if you need I can send to you again.

thanks

**Comment by ttrigui** [comment] 2020-04-15 21:40
#985 this is the same problem that was observed when over_boundary_block_mode is set to 1 (processing more blocks at the boundaries)

**Comment by hassount** [comment] 2020-04-17 05:14
@xuguangxin can you please check if #1217 addresses this ?

**Comment by xuguangxin** [comment] 2020-04-17 05:41
@hassount , I tried 3 times, all md5 are matched. 

yes, it's fixed.

**Closed** 2020-04-17 23:34 UTC
Labels: bug
