### ISSUE TITLE
Corrupted bitstream with -enc-mode 3

### ISSUE THREAD

**Issue by SmilingWolf** [OpenVisualCloud/SVT-AV1#633] opened 2019-09-23 20:12 UTC
SVT-AV1 commit: 0343007

System:
CPU: i7-4770 (with AVX2)
OS: Win7 64bit

Clip (compressed with FFV1): https://mega.nz/#!FpAjkSTT!7VDpPDSdYh6QPy2NlexwrKNJAzZNfXmiqvpjGJOHwR0
Encoded file: [svtav1.cq16sp3.bugRepro.zip](https://github.com/OpenVisualCloud/SVT-AV1/files/3643945/svtav1.cq16sp3.bugRepro.zip)

Cmdlines used:
```
# SvtAv1EncApp.exe -i svtav1.cq16sp3.bugRepro.yuv -b svtav1.cq16sp3.bugRepro.ivf -w 1920 -h 1080 -q 16 -scm 0 -enc-mode 3 -fps-num 24000 -fps-denom 1001 -intra-period 23
# aomdec.exe -o /dev/null svtav1.cq16sp3.bugRepro.ivf
Warning: Failed to decode frame 2: Corrupt frame detected
Warning: Additional information: Failed to decode tile data
```

dav1d can decode the clip, but there are noticeable artifacts:
![032](https://user-images.githubusercontent.com/4309301/65458958-181f5500-de4f-11e9-8e04-79b34da3e435.png)

**Comment by JackZhouVCD** [comment] 2019-09-23 23:41
possible duplicate of #538 , I will take a look into this, thanks for reporting this issue!

**Comment by SmilingWolf** [comment] 2019-09-24 05:46
Tested without setting `-intra-period 23`, the error is still present.
Encoded file: [svtav1.cq16sp3.bugRepro.zip](https://github.com/OpenVisualCloud/SVT-AV1/files/3645386/svtav1.cq16sp3.bugRepro.zip)

I have noticed, however, that this problem only appears when using `-enc-mode 3`, whereas `-enc-mode 2` and `-enc-mode 4` work. Encoded files at modes 2 and 4: [enc-mode2and4.zip](https://github.com/OpenVisualCloud/SVT-AV1/files/3645422/enc-mode2and4.zip)
Those two have been encoded without setting `-intra-period 23`, too.

**Comment by JackZhouVCD** [comment] 2019-09-24 19:07
Thanks for the issue report! I ran a bisect and found that this is caused by PR #588. We will look into this and get it fixed as soon as possible.

**Comment by SmilingWolf** [comment] 2019-10-15 19:35
I can still reproduce the issue with a build from commit 91fc5b17, is there any news on this?

I'm attaching the generated IVFs, both with -intra-period set to 23 and without. Both are defective.

[bugRepro.91fc5b17.zip](https://github.com/OpenVisualCloud/SVT-AV1/files/3731122/bugRepro.91fc5b17.zip)

**Comment by JackZhouVCD** [comment] 2019-10-15 19:55
> I can still reproduce the issue with a build from commit [91fc5b1](https://github.com/OpenVisualCloud/SVT-AV1/commit/91fc5b17978d23a593cc48d04488573ae64dfb51), is there any news on this?
> 
> I'm attaching the generated IVFs, both with `-intra-period 23` and without. Both are defective.
> 
> [bugRepro.91fc5b17.zip](https://github.com/OpenVisualCloud/SVT-AV1/files/3731122/bugRepro.91fc5b17.zip)

Thanks for the reminder. We have yet to come up with a fix, but I have found two ways to work around this issue:
- turn on screen content mode with `-scm 1` in the command that you are using to encode the clip
- if you don't want to turn on screen content mode, then you will have to use 64x64 superblocks instead of 128x128. This is not yet implemented as a functioning commandline argument, but it could manually be set in the code by adding this line of code:

```c++
sequence_control_set_ptr->static_config.super_block_size = 64;
``` 

after this block of code:

https://github.com/OpenVisualCloud/SVT-AV1/blob/eb2b6551d6559c039b8e1036167f51351e9870ab/Source/Lib/Encoder/Codec/EbEncHandle.c#L1949-L1954

**Comment by hassount** [comment] 2019-10-25 05:16
The depth setting is inappropriate, this will be fixed when the presets get updated

**Comment by lijing0010** [comment] 2019-11-06 06:41
@SmilingWolf , you can try the below PR(could be a temporal work around)
https://github.com/OpenVisualCloud/SVT-AV1/pull/768

**Comment by SmilingWolf** [comment] 2019-11-06 18:04
Using #768 the problem seems to be fixed.

**Closed** 2019-11-19 16:23 UTC
Labels: P1, bug
