### ISSUE TITLE
lm-opt branch uses illegal instructions on AVX2

### ISSUE THREAD

**Issue by EwoutH** [OpenVisualCloud/SVT-AV1#275] opened 2019-05-24 10:30 UTC
@kirithika7 The [lm-opt](https://github.com/hguermaz/SVT-AV1/tree/lm-opt) branch over at [hguermaz/SVT-AV1](https://github.com/hguermaz/SVT-AV1) tries to use illegal instructions (I guess AVX512) on my system. Happened on multiple commits.

_Config_

- **Video:** Morocco (1080p 8-bit 4:2:0)
- **System:** Intel (28c/56t, AVX2), 128GB DDR4, Linux Mint

```
/home/ewouth/SVT-AV1/Bin/Release/SvtAv1EncApp -i Morocco-1000.y4m -n 240 -enc-mode 8;
-------------------------------------------
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.4.0
SVT [build]  :  GCC 7.3.0        64 bit
LIB Build date: May 24 2019 06:21:22
-------------------------------------------
Number of logical cores available: 56
Number of PPCS 157
-------------------------------------------
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 8
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 1920 / 1080
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 19001 / 317 / 64 / 1
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 4 / 0 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 50 / 33 / 0
-------------------------------------------
Encoding          Illegal instruction
```

**Comment by EwoutH** [comment] 2019-05-24 10:47
Also got an error on a Google Cloud instance (Skylake with AVX512).

- [Google-Cloud-SVT-AV1-Error.txt](https://github.com/OpenVisualCloud/SVT-AV1/files/3216475/Google-Cloud-SVT-AV1-Error.txt)

**Comment by kirithika7** [comment] 2019-06-03 04:24
@EwoutH These errors couldn't be reproduced on GCC version 5.4.0.I shall update GCC to latest version and check.

**Comment by EwoutH** [comment] 2019-06-03 05:43
Thanks for looking into this. The error still persists with the latest commits. Build commands:
```
git clone -b lm-opt https://github.com/hguermaz/SVT-AV1.git;
cd SVT-AV1;
./Build/linux/build.sh release;
```

**Comment by EwoutH** [comment] 2019-06-07 16:23
@kirithika7 Any update? Issue still persist on my end.

**Comment by EwoutH** [comment] 2019-06-12 22:32
Issue still persists.

**Comment by lzhangnj** [comment] 2019-06-12 23:22
@EwoutH As shown in your attached Google Cloud txt, Commit 7f8aa222 used variables in _mm512_slli_epi32() and _mm512_srai_epi32()'s last arguments, which must be an const integer instead. It's a bug though some compilers may tolerate. Could you please ask the author to fix?

**Comment by EwoutH** [comment] 2019-06-13 00:18
@lzhangnj Thanks for the insight, @srikanthkurapati and @kirithika7 could one of you fix that?

A rebase of the branch would also be amazing, if reasonably possible.

**Comment by srikanthkurapati** [comment] 2019-06-13 12:49
Hi,
@EwoutH @lzhangnj 

We have pushed a patch to the lm-opt branch. We have checked using GCC 7.3.0 on CentOS 7.5.1804 

Please pull in the latest changes and see if it resolves the compiler errors for you.

**Comment by EwoutH** [comment] 2019-06-13 13:19
@srikanthkurapati Thanks for the patch. For some reason is still gives the _Illegal instruction_ output on my  Gentoo Linux system (GCC 7.3.0).

On the Google Cloud instance (GCC 6.3.0) it fails to build now. Here is a small part of the error log:

```
/usr/lib/gcc/x86_64-linux-gnu/6/include/avx512fintrin.h:1313:20: error: the last argument must be an 8-bit immediate
   return (__m512i) __builtin_ia32_psradi512_mask ((__v16si) __A, __B,
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         (__v16si)
         ~~~~~~~~~   
         _mm512_undefined_epi32 (),
         ~~~~~~~~~~~~~~~~~~~~~~~~~~
         (__mmask16) -1);
         ~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/avx512fintrin.h:1313:20: error: the last argument must be an 8-bit immediate
   return (__m512i) __builtin_ia32_psradi512_mask ((__v16si) __A, __B,
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         (__v16si)
         ~~~~~~~~~   
         _mm512_undefined_epi32 (),
         ~~~~~~~~~~~~~~~~~~~~~~~~~~
         (__mmask16) -1);
         ~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/avx512fintrin.h: In function ‘av1_inv_txfm2d_add_32x32_avx512’:
/usr/lib/gcc/x86_64-linux-gnu/6/include/avx512fintrin.h:1313:20: error: the last argument must be an 8-bit immediate
```

**Comment by srikanthkurapati** [comment] 2019-06-14 06:13
Hi Ewouth,

Can u please share the entire error log so that all such issues can be fixed once for all.

**Comment by EwoutH** [comment] 2019-06-14 12:40
I can't figure out how to copy the full CLI output from a Google Cloud instance. Here two more parts:
[log3.txt](https://github.com/OpenVisualCloud/SVT-AV1/files/3290627/log3.txt)
[log4.txt](https://github.com/OpenVisualCloud/SVT-AV1/files/3290626/log4.txt)

**Comment by srikanthkurapati** [comment] 2019-06-14 13:17
Copy paste will be difficult please use the below linux command to redirect stderr and stdout to a file.
./build.sh 2> error.log 

then u can download from the instance and upload here.

Thank you.

**Comment by EwoutH** [comment] 2019-06-14 14:00
For some reason it doesn't log the full output: [error2.log](https://github.com/OpenVisualCloud/SVT-AV1/files/3290909/error2.log)

Try building with _release_ on your system, it gives more errors than without.

**Comment by srikanthkurapati** [comment] 2019-06-14 14:07
We are not facing any such issues in our compilations so far.  Nevertheless based on the errors reported we will give push a Patch on Monday. 

Thank you.

**Comment by EwoutH** [comment] 2019-06-17 09:21
`Encoding          Illegal instruction`

Issue still persists unfortunately.

**Comment by srikanthkurapati** [comment] 2019-06-17 15:46
please share output of ./build.sh 2> compilation.log

Attaching sample from one of our setups with GCC 7.3.0 on CentOS 7.5.1804. 

We need to check if any other issue is cause the above. So far we have not faced this in our linux servers.

[build output on linux.txt](https://github.com/OpenVisualCloud/SVT-AV1/files/3297768/build.output.on.linux.txt)

**Comment by lzhangnj** [comment] 2019-06-17 22:02
For _mm512_srai_epi32() and _mm256_slli_epi16() etc, the shift bit number must be const integer for some compilers, such as deterministic 0, 1, or 2, instead of bit or bd which are variables. One solution is to put the shift bit variable into a __m128i register first, and call _mm512_sra_epi32() and _mm256_sll_epi16() instead. Some compilers can do this automatically I guess, but some others cannot.

**Comment by EwoutH** [comment] 2019-06-17 22:28
With GCC 9.1.0, 8.3.0 and 7.3.0:
- [SVT-AV1-release-gcc9.txt](https://github.com/OpenVisualCloud/SVT-AV1/files/3299074/SVT-AV1-release-gcc9.txt)
- [SVT-AV1-release-gcc8.txt](https://github.com/OpenVisualCloud/SVT-AV1/files/3299075/SVT-AV1-release-gcc8.txt)
- [SVT-AV1-release-gcc7.txt](https://github.com/OpenVisualCloud/SVT-AV1/files/3299076/SVT-AV1-release-gcc7.txt)

**Comment by srikanthkurapati** [comment] 2019-06-18 05:08
Since compilation is going fine as observed in the attachments is there a need to fix issue for other compilers. 

@lzhangnj we have changed the datatype to const int to solve the problem.

**Comment by JackZhouVCD** [comment] 2019-10-03 22:17
All of the features and changes on `hguermaz/SVT-AV1/lm-opt` has been ported to Master already. As such, it is not longer an active branch.

**Closed by JackZhouVCD** 2019-10-03 22:17 UTC
